var AppConfig = {
  'THAI_TEMPLATE_FILE_ID': '1G8YE7VZbqgVlalEcdXLxXPyOjVEjchiBbHoB-zbT1j4',
  'ENGLISH_TEMPLATE_FILE_ID': '1rRURiK5OUESWlpGDkhPw0uRvlTcXmqrLdKbZhTQx56Y',
  'DESTINATION_FOLDER_ID': '1Gb4z1Ajad2-OGLls029Tdc5_UK79Frik',
  'SIGN_IMAGE_FOLDER_ID': '1h3hA8syODMLX5pkaXMJ38ZPs5x90huJm',
  'LOG_SPREADSHEET_ID': '1MqNUqyOZxsU9M6uzAEgjHkSeJo-XvZ8otGK5rWnqFcQ',  
  'LOG_SHEET_NAME': 'log',
}